const fs = require("fs");
const PNG = require("pngjs").PNG;

var data = fs.readFileSync(process.argv[2]);
var image = PNG.sync.read(data);

let binary;
let binPos = 0;

if (process.argv[3] == "fullscreen") {
    binary = Buffer.alloc(image.width * image.height);
    const name = process.argv[4];

    let header = `
/*
* ${name}.h
*
* Auto-generated by ImageConvert on ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
*/ 

#ifndef ${name.toUpperCase()}_H_
#define ${name.toUpperCase()}_H_

`;
    
    header += `static const char IMG_STARTUP[1024] = {\n\t`;
    
    for (let y = 0; y < 64; y++) {
        for (let x = 0; x < 128; x += 8) {
            header += "0x";
            let pixelByte = 0;
            for (let i = 0; i < 8; i++) {
                let color = image.data[y * 128 * 4 + (x + i) * 4] == 0x00;
                pixelByte += color << (7 - i);
            }
            binary[binPos] = pixelByte;
            binPos++;
            header += pixelByte.toString(16) + ", ";
        }
        header += "\n\t";
    }
    
    header += `};\n#endif /* ${name.toUpperCase()}_H_ */`
    
    fs.writeFileSync(name + ".h", header);
    fs.writeFileSync(name + ".bin", binary);
} else if (process.argv[3] == "font") {
    const charWidth = parseInt(process.argv[4]);
    binary = Buffer.alloc(image.height * (image.width / charWidth));

    let header = `
/*
* font_${charWidth}x${image.height}.h
*
* Auto-generated by ImageConvert on ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
*/ 

#ifndef FONT_${charWidth}x${image.height}_H_
#define FONT_${charWidth}x${image.height}_H_

`;
    
    header += `const __flash char FONT_${charWidth}x${image.height}[][${image.height}] = {\n`;
    
    for (let character = 0; character < image.width; character += charWidth) {
        header += "\t{\n";
        for (let y = 0; y < image.height; y++) {
            let currByte = 0;
            header += "\t\t0b";
            for (let x = 0; x < charWidth; x++) {
                let color = image.data[y * image.width * 4 + (character + x) * 4 + 3] == 0xFF;
                currByte += color << (charWidth - x - 1);
                header += color ? '1' : '0';
            }
            binary[binPos] = currByte;
            binPos++;
            header += ",\n";
        }
        header += "\n\t},\n";
    }
    
    header += `};\n#endif /* FONT_${process.argv[4]}x${image.height}_H_ */`;
    
    fs.writeFileSync(`font${process.argv[4]}x${image.height}.h`, header);
    fs.writeFileSync(`font${process.argv[4]}x${image.height}.bin`, binary);
} else {
    console.log("Usage:\nnode makeHeader.js <file> fullscreen|font <image name>|<char width>");
}